# Source: nri-bundle/charts/nri-kube-events/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
data:
  config.yaml: |-
    sinks:
    - name: newRelicInfra
      config:
        agentEndpoint: http://localhost:8001/v1/data
        clusterName: {{ .Values.cluster_name }}
        agentHTTPTimeout: 30s
metadata:
  name: nri-bundle-nri-kube-events-config
  namespace: monitoring
  labels:
    app: nri-kube-events
    app.kubernetes.io/name: nri-kube-events
    helm.sh/chart: nri-kube-events-1.0.0
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/version: "1.1.0"

---
# Source: nri-bundle/charts/nri-prometheus/templates/configmap.yaml
kind: ConfigMap
metadata:
  name: nri-bundle-nri-prometheus-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: nri-prometheus
    helm.sh/chart: nri-prometheus-1.0.1
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/version: "1.3.0"
apiVersion: v1
data:
  config.yaml: |
    cluster_name: {{ .Values.cluster_name }}
    require_scrape_enabled_label_for_nodes: true