# Source: nri-bundle/charts/nri-metadata-injection/templates/mutationwebhookconfiguration.yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: nri-bundle-nri-metadata-injection
  labels:
    app.kubernetes.io/name: nri-metadata-injection
    helm.sh/chart: nri-metadata-injection-1.0.0
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/version: "1.2.0"
webhooks:
  - name: metadata-injection.newrelic.com
    clientConfig:
      service:
        name: nri-bundle-nri-metadata-injection
        namespace: monitoring
        path: "/mutate"
      caBundle: ""
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
