# Source: nri-bundle/charts/kube-state-metrics/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    helm.sh/chart: kube-state-metrics-2.3.0
    app.kubernetes.io/instance: nri-bundle
  name: nri-bundle-kube-state-metrics
imagePullSecrets:
  []

---
# Source: nri-bundle/charts/nri-prometheus/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nri-prometheus
  namespace: monitoring
  labels:
    app.kubernetes.io/name: nri-prometheus
    helm.sh/chart: nri-prometheus-1.0.1
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/version: "1.3.0"

---
# Source: nri-bundle/charts/nri-kube-events/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nri-kube-events
    app.kubernetes.io/name: nri-kube-events
    helm.sh/chart: nri-kube-events-1.0.0
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/version: "1.1.0"
  name: nri-bundle-nri-kube-events
  namespace: monitoring

---
# Source: nri-bundle/charts/newrelic-infrastructure/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: monitoring
  labels:
    app: newrelic-infrastructure
    chart: newrelic-infrastructure-0.13.33
    release: "nri-bundle"
  name: nri-bundle-newrelic-infrastructure

---
# Source: nri-bundle/charts/nri-metadata-injection/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nri-bundle-nri-metadata-injection
  namespace: monitoring
  labels:
    app.kubernetes.io/name: nri-metadata-injection
    helm.sh/chart: nri-metadata-injection-1.0.0
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/version: "1.2.0"