apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemoveDuplicates":
         enabled: false
      "RemovePodsViolatingInterPodAntiAffinity":
         enabled: true
      "LowNodeUtilization":
         enabled: true
         params:
           nodeResourceUtilizationThresholds:
             thresholds:
               "cpu" : {{ .Values.thresholds_cpu }}
               "memory": {{ .Values.thresholds_memory }}
               "pods": {{ .Values.thresholds_pods }}
             targetThresholds:
               "cpu" : {{ .Values.targetThresholds_cpu }}
               "memory": {{ .Values.targetThresholds_memory }}
               "pods": {{ .Values.targetThresholds_pods }}