apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-load-balancer-controller-role
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/version: v2.1.1
    helm.sh/chart: aws-load-balancer-controller-1.1.2
rules:
  - apiGroups: ["elbv2.k8s.aws"]
    resources: [targetgroupbindings]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch]
  - apiGroups: ["networking.k8s.io"]
    resources: [ingressclasses]
    verbs: [get, list, watch]
  - apiGroups: ["", "extensions", "networking.k8s.io"]
    resources: [services, ingresses]
    verbs: [get, list, patch, update, watch]
  - apiGroups: [""]
    resources: [nodes, secrets, namespaces, endpoints]
    verbs: [get, list, watch]
  - apiGroups: ["elbv2.k8s.aws", "", "extensions", "networking.k8s.io"]
    resources: [targetgroupbindings/status, pods/status, services/status, ingresses/status]
    verbs: [update, patch]