apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-load-balancer-controller-leader-election-role
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/version: v2.1.1
    helm.sh/chart: aws-load-balancer-controller-1.1.2
rules:
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [create, get, update]
  - apiGroups: [""]
    resources: [configmaps]
    resourceNames: [aws-load-balancer-controller-leader]
    verbs: [get, patch, update]